### ISSUE TITLE
TLE's

### ISSUE THREAD

**Issue by SamuelHiatt79** [rt-bishop/Look4Sat#118]
Where are the TLE's stored? I'm looking for USA 144. I cant find it on celectrack.org or spacetrack. The TLE I have lags behind about 30-45 mins from what the app shows.

**Comment by rt-bishop** [comment]
Hey @SamuelHiatt79! The app doesn't store TLEs as files locally, once the data is downloaded it goes directly into the database. All the sources URLs you can find in [this file](https://github.com/rt-bishop/Look4Sat/blob/devel/domain/src/main/java/com/rtbishop/look4sat/domain/source/Sources.kt). 

Most of the data comes from Celestrak, but some comes from AMSAT, R4UAB and McCants, which you're probably going to be interested in. If you are aware of any other good sources, please do let me know.
