### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by zWhdmB5T** [rt-bishop/Look4Sat#123]
Thank you!

Thank you for your project and software!

Thank you for maintenance in the past and in the future!

Kind regards and season's greetings!

**Comment by rt-bishop** [comment]
Thank you so much for these kind words! I'm really happy you're enjoying the app. Getting positive feedback is crucial and is always a good inspiration to continue making and sharing. I'm becoming a daddy very soon and won't have too much time for my hobbies and projects but I do have a new version of Look4Sat in mind and will release it at some point this year. Cheers!
