### ISSUE TITLE
Map view does work on devel branch

### ISSUE THREAD

**Issue by Raviu56** [rt-bishop/Look4Sat#132]
Map view works on v3.1.4 but not on devel branch. It displays nothing other than a map and user point. No satellites info.

**Comment by rt-bishop** [comment]
Yeah, this is not an issue. The devel branch is a work in progress, it's a half-baked next version planned for some time in the future that uses Jetpack Compose for UI. All the old UI system components were removed but not all of them were rebuilt in Compose yet. If you need the last stable commit of the currently released app you could just check out the v3.1.4 tag or data_update_fix branch.
