### ISSUE TITLE
Satellite selection is lost after TLE update

### ISSUE THREAD

**Issue by therman89** [rt-bishop/Look4Sat#14]
If I have selected satellites in the main view and I update the TLE date, the satellite list is gone, because the selection is cleared. Selection should be stored in memory to recover it after TLE update.

**Comment by rt-bishop** [comment]
I'll address the issue as soon as I can, I understand this is quite annoying. Working on rewriting some parts of predict4java lib now, will do this one straight after.

**Comment by rt-bishop** [comment]
Fixed in recent cf86892ad574d3edc9fb44bc9f2a0ca8ea3637d5 commit
