### ISSUE TITLE
Sporadically the pass list shows no passes and an endless "refresh" indicator

### ISSUE THREAD

**Issue by ryandzink** [rt-bishop/Look4Sat#18]
I've had this happen a number of times, but can't figure out what circumstances cause it to happen.

When I go to the pass list, I see what looks like an empty pass list and a refresh indicator that seems to go forever. However, the countdown timer at the top is accurate, so this looks like a display bug.

![Screenshot_20200708-155752](https://user-images.githubusercontent.com/13768946/88483556-858f8c80-cf1d-11ea-88fb-e46916aadd2b.jpg)

If I got at the pass list from a specific pass polar view, and I try to go back to it, I get this screen with what looks like default/unformatted strings.

![Screenshot_20200708-155741](https://user-images.githubusercontent.com/13768946/88483561-888a7d00-cf1d-11ea-94a5-656faf9cee99.jpg)

I haven't found a way to resolve this except by closing and reopening the app.

**Comment by rt-bishop** [comment]
Hello @ryandzink! I know of this strange bug, it's quite hard to reproduce though as it just occurs randomly. I think I might've done something wrong with the passes calculation threading. I'll look into it and hopefully fix it by the next release.

**Comment by rt-bishop** [comment]
Fixed in f338a05
