### ISSUE TITLE
[FR] world map zoom

### ISSUE THREAD

**Issue by ildar** [rt-bishop/Look4Sat#19]
would be great even without care of datalization

**Comment by rt-bishop** [comment]
Hey, thanks for the feature request! I'm still working on the OpenStreetMaps integration for v1.5 which will obviously include this feature. There are some complications but hopefully I'll finish within a couple of weeks.

**Comment by ildar** [comment]
That's... shocking )))
What's the purpose for using OSM? I'm sure it'll make apk many times
heavier and there must be a noticeable reason for that.

**Comment by rt-bishop** [comment]
Well, not really, the osmdroid library is exceptionally lightweight. Just checked the apk size: 2.6MB vs 2.5MB before. And I haven't even removed the legacy map code and resources yet. I will also limit the max zoom level to 6-7 (4-16MB of tiles cache max) cause we're watching satellites, not the map itself. Tiles are being cached automatically but there will be an option to pre-download them for a full offline experience. 
I wanted some proper maps funcionality for a long time and also it's the first step for the upcoming user interface revamp.

**Comment by rt-bishop** [comment]
Feature demo added in recent v1.4.8, more work on it in the future release
