### ISSUE TITLE
Satellites currently overhead show up even in future passes

### ISSUE THREAD

**Issue by ryandzink** [rt-bishop/Look4Sat#24]
I don't know if this is expected behavior but when you look at future satellite passes of a satellite that is currently overhead, you see the current satellite location on both the current and future passes.

As an example, here is an SO-50 satellite pass showing both the current pass and the next one scheduled, and you can see the current satellite location on the next pass as well.

**Active pass:**
![Screenshot_20200912-085831](https://user-images.githubusercontent.com/13768946/93004314-ae360a80-f4fa-11ea-888b-076c7ef4dcfa.jpg)

**Next pass showing current position:**
![Screenshot_20200912-085824](https://user-images.githubusercontent.com/13768946/93004324-bee68080-f4fa-11ea-9151-3b0740ae6cd3.jpg)

I'm not sure if it is intended to be this way, but it did look a bit odd the first couple of times I saw it until I put 2 and 2 together.

**Comment by rt-bishop** [comment]
Hey Ryan! To be honest, initially it happened unintentionally, but I really liked it as it helped a lot with testing. So I decided to keep it that way. Also it led me to the idea of making a separate PolarView fragment with all the sats currently overhead, which I'm going to implement some time in the future after the complete UI revamp. Do you think it's an issue, shall I keep it open?)

**Comment by ryandzink** [comment]
I don't think it's a big enough issue to be fixed, I think we can close it. That all satellites overhead view does sound interesting!
