### ISSUE TITLE
Improve sunlight readabilitysatellite/polar view [feature request]

### ISSUE THREAD

**Issue by sbridger** [rt-bishop/Look4Sat#28]
I notice that readability is difficult in direct sun. Unfortunately the use case is often laying the phone horizontal which is just the worst for sky reflection.

a) Make the track arc a much thicker line, there is no need for it to be fine
b) make the track line white (best brightness) or a brighter color 
c) same for the satellite dot.

For (b) I'm not sure what is best as it is a matter of contrast and the front surface reflection is white-blue. In a quick test magenta seemed brighter than red, and more contrasty that cyan.

There is a lot of grey text, and full white would be better. 
Of course at night perhaps not, so perhaps a global definition of "white" or a global font brightness is needed.

(I find the current UI/product design fashion for grey text on grey backgrounds pretty unreadable)

**Comment by rt-bishop** [comment]
Hey! Thanks for the request. All your suggestions sound reasonable but I'll have to postpone them for a bit because I've got a major UI revamp planned for the next few months. So stay tuned!
