### ISSUE TITLE
ISS times are incorrect, out by about 5 minutes!! Location confirmed.

### ISSUE THREAD

**Issue by hayden-t** [rt-bishop/Look4Sat#32]
I have verified my location.  And tracked ISS with SSTV transmissions 2 days in a row now. And tracker app is wrong, and ive compared it with other websites to confirm this. Its about 5 minutes too early.

Im located in NSW australia. As an example use coords -31, 152 i put them in app, and then compare with heavens above website, 5 minutes difference. The app is wrong, confirmed by actual radio tracking.

**Comment by rt-bishop** [comment]
Hey Hayden! My raspberry pi weather station, my radio observations and I - we all disagree with you. Heavens above and other tracking wibsites are not a reference for me, only Space-Track and Celestrak are. So I compared the app predictions with Gpredict ones, as they both use Celestrak data, and everything is correct. If you said 5 seconds difference, then I get it. But 5 minutes.. means you're doing something wrong.

Freshly updated TLE, same location, the result...

![gpredict_loc](https://user-images.githubusercontent.com/44072814/95307165-356b6980-0880-11eb-8ffc-de5535f22e3a.png)
![look4sat_loc](https://user-images.githubusercontent.com/44072814/95307193-3d2b0e00-0880-11eb-9b9a-9b0063f87f35.png)
![gpredict_passes](https://user-images.githubusercontent.com/44072814/95307208-40be9500-0880-11eb-9c7e-1cdd5442d945.png)
![look4sat_passes](https://user-images.githubusercontent.com/44072814/95307217-43b98580-0880-11eb-851f-1731ebabf83e.jpg)

**Comment by hayden-t** [comment]
I just used heavens above as an example, please tell me how to get data you believe ? as Im not sure how to use those websites. please show somewhere i can put in my coords, and get the passes to compare.

**Comment by hayden-t** [comment]
please dont just close this ticket without working through it with me

**Comment by rt-bishop** [comment]
@hayden-t No worries, if your TLE data is up to date and the location you set in both the app and the website are the same, then you will get the same passes. 
I think I know what the issue is as I've just checked the heavens above website. It considers the "pass start" the time when the satellite reaches the 10 degrees altitude, whether Look4Sat shows the full pass from the moment it rises above the horizon. If you click on the pass to see the details on the heavens above website, you'll see that there is a list with separate events and times for them. Could you compare the data you get and post here what you find? The time difference I get is about 5 seconds.

**Comment by hayden-t** [comment]
sorry, so busy, will look into this Look4Sat  website

**Comment by hayden-t** [comment]
so it seems my tle data was out of date as doing so has moved iss pass later about gap i reported. which is what i was hoping that id just needed to do something different. so may i suggest some change in the app to make this more clear. as id thought pulling down the list of passes screen for a spinny refresh would have done this. what does that do then ??? also when you do go to tle import from web, it appears to be just a screen to add sources, and you just click ok when they are done. it does not appear to be a screen that actually downloads them, maybe the button should say download/update instead of ok, also maybe a progress meter/dialog ?? as i had no idea it was actually downloading it until i saw a quick flash up one liner that said it had downloaded which is easy to miss or not read in time. also maybe some suggestion on how often this should be updated ? maybe even an option for auto update ? thanks.

**Comment by ryandzink** [comment]
For what it's worth, I also had this issue. It took me a few tries of only picking up the satellite when Look4Sat said it was almost at LOS before I compared to other apps and noticed the discrepancy of ~5 minutes and forced an update. I'm not sure if the recent orbit change means the TLE I had gotten a couple of months ago was out of date?

**Comment by rt-bishop** [comment]
A couple of months? Well, generally it's advised to update TLEs every week or so, the error of SGP4 is about 1km/day. Of course the orbit change means the TLE becomes out of date. I'm not sure I understand what the suggestions is... do you want the updates to be automated? Or shall I put a message somewhere saying "Weekly updates are recommended"?

**Comment by ckuethe** [comment]
"Update your TLEs Weekly" message would probably be easiest for you. 

Auto update after a week, plus allowing immediate refreshes if you add a new source or if you know a source *just* updated the data would be nice
