### ISSUE TITLE
[Suggestion] Hide "null" downlink / uplink frequencies

### ISSUE THREAD

**Issue by shuyuan-liu** [rt-bishop/Look4Sat#35]
Hi @rt-bishop I've been using Look4sat for NOAA, meteor, ISS and amateur satellite passes and it works great with a clean UI.

I do have a suggestion that in the polar view, we hide uplink / downlink frequencies that are "null" as they are usually not very helpful (for me at least) and take up space. I recognise that this might be useful if people wanted to confirm that there's no uplink / downlink, so maybe make a switch for it in the settings?

Before:
![Before](https://user-images.githubusercontent.com/41851763/100265808-b671e380-2f48-11eb-99e4-ae1ffec9eb59.jpg)

What I'm thinking of:
![After](https://user-images.githubusercontent.com/41851763/100265833-beca1e80-2f48-11eb-9537-dd539278b2a0.jpg)

**Comment by rt-bishop** [comment]
Hey there @shuyuan-liu! Thank you very much for your suggestion) Actually at the moment I'm working on Look4Sat v2.0 with huge changes to the UI. In the developer build there are no "null" freqs any more. There are a LOT of changes, if everything goes well I will release it in 4-5 days. So stay in touch and thank you for using the app!
