### ISSUE TITLE
Map view wraps around vertically when zoomed out

### ISSUE THREAD

**Issue by shuyuan-liu** [rt-bishop/Look4Sat#42]
If I zoom out in the map view, copies of the world map are displayed below and above the normal one, like they are tiling to fill the empty space above the North pole and below the South pole. This might be intended in Openstreetmap but it does look counterintuitive (for me at least).

![Screenshot_20201216-230825~2.png](https://user-images.githubusercontent.com/41851763/102417923-9b990900-3ff4-11eb-867e-a35f5cba665b.png)

**Comment by rt-bishop** [comment]
Out of interest, what's the resolution of your screen? There are settings in the OSM lib to enable the vertical/horizontal infinite map scroll. Both these are disabled in Look4Sat. Curious... it also shouldn't let you zoom out more than the minimal zoom level. I'll do more testing with different screen sizes and I'll fix it in the next release. Thanks for reporting it!

**Comment by shuyuan-liu** [comment]
Hi there. My resolution is 1080×2340, 422 DPI. My device is a Xiaomi 9 SE on AOSP Android 11, if that's relevant.
