### ISSUE TITLE
Valid Locators Are Not Accepted

### ISSUE THREAD

**Issue by DC7IA** [rt-bishop/Look4Sat#44]
Hi,

some locators aren't accepted by Look4Sat. It says they are "invalid".

Version: 2.0.1
Locator: JO51BJ

**Comment by DC7IA** [comment]
Weirdly enough, it worked a few minutes later for me.

@Konradrunfdunk is the original observer of this bug

**Comment by DC7IA** [comment]
Alright, I narrowed it down to being upper-case. While `JO51BJ` does not work, `JO51bj` does.

**Comment by DC7IA** [comment]
Look4Sat should tell users how to type the locator or ignore case, imho.

**Comment by Konradrundfunk** [comment]
It seams to me that the funktion setPositionFromQth in the class Prefsfragment is stricktly set to thoose values.

**Comment by rt-bishop** [comment]
Hey everyone and thanks for reporting this! To be honest I didn't expect the letter case to be such an issue for so many users. I'll definitely fix it with the next update, so the case will be converted internally, accepting those wrongly "invalid" locators. Will also create some unit tests to cover this issue.
