### ISSUE TITLE
Feature request: Edit satellites frequencies

### ISSUE THREAD

**Issue by ea5wa** [rt-bishop/Look4Sat#45]
It will be nice to have the possibility to edit the uplink/downlink frequencies and also the possibility to enable or not displaying those frequencies.
Sometimes we are only interested in one frequency

**Comment by rt-bishop** [comment]
Hey there! Thanks, @ea5wa, for your support and this suggestion! However, to me this looks like a very narrow use case. I can understand when a radio amateur wants to add the freqs missing in the SatNOGs DB, but hiding/showing... I'll leave this issue open for now just to see what other people say and how many actually need it.

**Comment by ea5wa** [comment]
Some people are not interested on telemetry or cw beacon. They only want to know the transponder frequencies....
