### ISSUE TITLE
Pressing ▶ before satellite list loads clears satellite selection

### ISSUE THREAD

**Issue by shuyuan-liu** [rt-bishop/Look4Sat#46]
Steps to reproduce:
- Go to a tab other than Satellites.
- Switch back to Satellites.
- Before the spinning animation disappears, i.e. before the satellite list is displayed, press the ▶ button at the bottom of the page.

Results:
- All previously selected satellites are deselected.
- No boxes are ticked in the Satellites tab, the Passes tab says "No upcoming passes", and the World Map tab doesn't show any satellites.

My suggestion is to hide or disable the ▶ button until the satellite list has loaded.

**Comment by rt-bishop** [comment]
Well spotted! Thank you very much indeed for the issue and for the steps to reproduce, really helpful. 
I'll make sure it's fixed with the next release.
