### ISSUE TITLE
Satllite dot on radar view becomes two dots as pass goes on

### ISSUE THREAD

**Issue by ryandzink** [rt-bishop/Look4Sat#51]
This behavior seems to have appeared in the past one or two updates.

What starts out as a single satellite dot on the radar view slowly splits apart as the pass goes on to show two dots at different points on the arc, with one traveling slightly slower than the other, and one of the two dots appearing "above" the red arc while the other is "below" the arc.

If I back out to the list of passes and then come back in to the radar view, there is once again only one satellite dot on the arc.
![Screenshot_20210409-080205](https://user-images.githubusercontent.com/13768946/116788342-e1afb000-aa5d-11eb-8774-27059d6e3758.jpg)

**Comment by ryandzink** [comment]
I wanted to update this to say this is an issue with the entire radar view. I usually don't have rotation turned on but when I did I got the following result. This issue seems to be triggered more often when turning off the screen when on the radar view and then turning it back on.
![Screenshot_20210504-073959](https://user-images.githubusercontent.com/13768946/117079077-ed1a0a00-acef-11eb-9f84-d8e2f2ae00c7.jpg)

**Comment by MondoBurrito** [comment]
Yes, I get this problem as well. I hope there is a fix soon.

**Comment by rt-bishop** [comment]
Hey guys. Thanks for reporting this. I've already fixed it in the dev build. Hopefully I'll ship it in a week or two maximum.

**Comment by ryandzink** [comment]
I see this is fixed in the latest release, thanks!

**Comment by MondoBurrito** [comment]
AWESOME! Thanks so much.
