### ISSUE TITLE
Suggestion for increasing screen readability

### ISSUE THREAD

**Issue by pedjas** [rt-bishop/Look4Sat#56]
Here is how Map view looks at my phone. Text is to large and some data is overlapping. Map copyright info is far to large.

![screenshot2](https://user-images.githubusercontent.com/2223601/118606279-813ba500-b7b7-11eb-8943-2ea1526e33ca.jpg)

It would help to have option to set font size for text.

Also, shorter generally recognized captions for field names may be used, like Alt instead Altitude, Lon instead of Longitude, Lat instead Latitude, etc...

Option to hide less needed satellite info on top of the map could be helpful. Only satellite ID is really important for everyday use. Other info is nice to see but not necessary.

Arrow that shows direction of satellite travel would be useful.

**Comment by pedjas** [comment]
Here is the same font issue in Passes page

![snapshot03](https://user-images.githubusercontent.com/2223601/118838241-d06ffb80-b8c5-11eb-9b25-3a59fc0d330e.png)

**Comment by rt-bishop** [comment]
I'm still pretty sure the reason for the issue is a global increased font setting. Would you please post here you hardware specs or phone model so I can set up a VM with exact same specs to see for myself.

**Comment by pedjas** [comment]
My phone is Xiaomi Redmi Note 4 but I guess you can get the same effect on any model, by just using increased font.
