### ISSUE TITLE
Don't show aiming icon when "Use sensors to rotate PolarView" is disabled

### ISSUE THREAD

**Issue by shuyuan-liu** [rt-bishop/Look4Sat#57]
First of all, thanks for adding the aiming feature - very useful for hand tracking satellites. However I think the icon should only be shown when "Use sensors to rotate PolarView" is enabled, because otherwise it is fixed at 0° due north and serves no purpose.

In the screenshot below I have disabled rotating PolarView, causing the aim icon to be fixed at the top of the PolarView:

![image](https://user-images.githubusercontent.com/41851763/118647468-4480a580-b7d9-11eb-8ead-d1c617fa9899.png)

**Comment by rt-bishop** [comment]
@shuyuan-liu makes perfect sense, thanks for reporting this. I've done like you requested as well as fixed the bugs with the recent 2.5.2 update. I'm glad people find the aiming feature useful. It was a lot easier to implement than I expected, wish I did it earlier.

**Comment by shuyuan-liu** [comment]
Thanks @rt-bishop, yes the aiming is quite handy. My phone's accelerometer is off by quite a few degrees though, will need to look for a way to calibrate it.

Reported problem solved, closing the issue
