### ISSUE TITLE
Selecting a satellite in the Satellites tab causes the list of satellites to scroll back to the top

### ISSUE THREAD

**Issue by ryandzink** [rt-bishop/Look4Sat#59]
This is admittedly a minor issue since I'm not changing the satellites I'm looking for on a regular basis, but something I thought I would mention. I think this started happening with the 2.5 update.

When I'm selecting a new satellite in the Satellites tab, as soon as I check the box the list of satellites scrolls back to the top. It does this even when the list of satellites is filtered with some text entered in the name field or filtered by transceiver mode.

**Comment by rt-bishop** [comment]
@ryandzink I've just removed the scrolling in the recent update. Let me know if it made it worse/better. Sometimes I'm too concentrated on the code internals and keep missing the user experience.
