### ISSUE TITLE
Feature request: Use of compass

### ISSUE THREAD

**Issue by Milan12332567** [rt-bishop/Look4Sat#6]
Hi, love the app, but id like the option to enable rotation of "radar" by compass.
Thanks

**Comment by therman89** [comment]
Up! A compass would be really handy for handheld satellite tracking.

**Comment by rt-bishop** [comment]
Thanks for your request, guys! Probably will add it within the next few weeks, first I need to peek on how other apps implemented this)))

**Comment by Milan12332567** [comment]
yeah, i need to track for HRPT so it whuld be great

**Comment by ryandzink** [comment]
I'm not sure if this should be its own request or not, but maybe a direction arrow on the radar view showing start and end of each pass? That info is on the pass listing view but not on the radar itself.

**Comment by rt-bishop** [comment]
Feature added in recent 80b62b46580735334c8acd2410b7b1831bc8cbbf
