### ISSUE TITLE
No new passes since update

### ISSUE THREAD

**Issue by dg9bja** [rt-bishop/Look4Sat#66]
Last night I updated to 2.5.4 and now I am missing new passes for my NOAA weather satellites. 
Was there a code change for this?

Anything it is a great app and I use it almost every day. Thank you!

Update:
Seems like the hours ahead settling seems to be ignored. Maybe it uses only default settings.

**Comment by rt-bishop** [comment]
Hey, thanks for reporting this, I'm already working on it. I decided to clean up, rename and move quite a few classes while cleaning up the codebase to get everything ready for the future features, and accidentally broke some things. Please, be patient, I should fix everything quite soon. At least it doesn't crash anymore while updating =)
