### ISSUE TITLE
v2.5.4 update seems to have broken pass progess indicator

### ISSUE THREAD

**Issue by ryandzink** [rt-bishop/Look4Sat#67]
I just updated to the latest version and the yellow progress bar of a current satellite pass in the Passes view does not seem to be showing anymore. I tried force closing the app and restarting, and didn't see any change. I'm attaching a screenshot of an instance where this is happening (CAS-4A).

![Screenshot_20210918-064029](https://user-images.githubusercontent.com/13768946/133893204-f86252bd-223d-4589-ab02-29edbf22b2c5.png)

**Comment by rt-bishop** [comment]
Yep! Thanks for reporting. Already working on that. After the recent Android 12 Api release and Java 11 becoming the new base quite a few things seem to be broken. I decide to fix the update crash issue first and now working on getting the rest of the stuff back to work. Won't be long.
