### ISSUE TITLE
Dash pointer ip

### ISSUE THREAD

**Issue by YamalQRA** [rt-bishop/Look4Sat#82]
Hello.  where can i read about dish positioner ip protocol

**Comment by rt-bishop** [comment]
Hello @YamalQRA! Sorry for the late reply. The antenna positioner ip protocol uses the message pattern declared in rigctl (part of hamlib) library. [See rigctl Commands](https://www.mankier.com/1/rigctl#Commands-rigctl_Commands). I'm planning on extending the functionality in the future, supplying the transceiver's mode type and frequency. Also, I had a request on supporting [Easycomm](https://www.mustbeart.com/software/easycomm.txt) message type, which I'll be adding as well.
