### ISSUE TITLE
Loading indicator while loading satellites

### ISSUE THREAD

**Issue by qwerty287** [rt-bishop/Look4Sat#84]
Hello and thanks for this nice app!

I think it would be nice to have a loading indicator while the satellites are loaded in the overview list or on the map. This is especially important if having many satellites - as example, select all of them and continue to the overview. Then you'll see a "No upcoming satellites" message which disappears after loading. There is also a display issue if clicking two times on the FAB in the bottom when viewing the passing overview. You'll see the selections list and if you click again, you'll the old list and in the background the "No upcoming satellites", which disappears after loading the satellite passings.

Version 3.0.0 from F-Droid.

**Comment by rt-bishop** [comment]
Hey @qwerty287, thank you very much indeed for reporting this issue! I'm really glad you like the app. 

I've just added the passes indicator to the dev build and fixed that nasty bug you reported, and some others. The latest version is being currently built and pushed to Google Play for their review. So I guess in about 3-4 hours it should be available for download.
