### ISSUE TITLE
Add Additional Mode LoRa Satellites and Frequencies

### ISSUE THREAD

**Issue by WA4OSH** [rt-bishop/Look4Sat#85]
- FEES                                        437.2 MHz
- FEES2                                      436 MHz
- FOSSASAT 2E1 through 2E6   401.7 MHz
- SATLLA 2A and 2B                  437.25 MHz and 2401 MHz
- MOCUBESAT-1                       436.9 MHz
- THINGSAT                               868.1 MHz and 2422 MHz
- GOSSAMER                             917.5 MHz
- BL-LORA-5                              432.662 MHz

source: https://tinygs.com/satellites

**Comment by rt-bishop** [comment]
Hey @WA4OSH, thanks for your request! 
Normally users should not insert their own data into the app, they need to interact with the data providers such as Celestrak for satellites and SatNOGS for transmitters. Are you associated with TinyGS? I guess this is something they can easily do, it's quite simple to add the data to SatNOGS, they have an amazing community and are fyllu open-source.
As an alternative - TinyGS can provide an API or just a simple db/text file on their website, that I can add to the app, and then all the new information collection will be done automatically every time you update the data via settings.
