### ISSUE TITLE
Some satellites are not shown even if clicked 

### ISSUE THREAD

**Issue by 1kaiser** [rt-bishop/Look4Sat#9]
Some satellites are not visible on map eg "aefh 4" but the "aehf 3" is available when seclected

**Comment by rt-bishop** [comment]
Yes, if you selected the satellite but it has no upcoming passes over your location, you won't see them on the map. Only the satellites with calculated upcoming passes are gonna be drawn. To see all of them simply increase the time for passes calculation from 8 hours to like 24 or smth. #wontfix #notabug
