### ISSUE TITLE
[Feature request] Auto-update satellite data

### ISSUE THREAD

**Issue by drws** [rt-bishop/Look4Sat#96]
Currently the user has to remember to update satellite data and perform it manually in the settings. Auto-update function would be a great improvement. There is no need for a background service, just a trigger upon application startup to automatically update data if a configurable interval of time has passed since (and maybe notify the user with some kind of a non-intrusive indication).

**Comment by rt-bishop** [comment]
Implemented in v3.1.2, update time was set to 48 hours to balance the update frequency and the TLE precision
